blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index'),
    path('<int:pk>/', views.BlogView.as_view(), name = 'blog'),
    path('entry/<int:pk>/', views.EntryView.as_view(), name = 'entry'),
    path('create_blog/', views.get_blog, name = 'get_blog'),
    path('create_author/', views.get_author, name = 'get_author'),
    path('create_entry/', views.get_entry, name = 'get_entry'),
    path('saved/', views.saved, name = 'saved'),
    path('register/', views.register, name='register'),
]

boards/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('blog/accounts/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls', namespace="blog"), name='blog'),
    path('polls/', include('polls.urls', namespace="polls")),
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

blog/models.py
from django.db import models

# Create your models here.


class Blog(models.Model):
    name = models.CharField(max_length=100)
    tagline = models.TextField()

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()

    def __str__(self):
        return self.name


class Entry(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    headline = models.CharField(max_length=255)
    body_text = models.TextField()
    pub_date = models.DateField()
    # mod_date = models.DateField()
    authors = models.ManyToManyField(Author)
    number_of_comments = models.IntegerField()
    # number_of_pingbacks = models.IntegerField()
    rating = models.IntegerField()

    def __str__(self):
        return self.headline

polls/models.py
# Create your models here.
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

blog/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.http import HttpResponseRedirect
from django.template import loader
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login

from django.views import generic
from .models import Blog, Author, Entry
from .form import BlogForm, SignUpForm, AuthorForm, EntryForm

# Create your views here.


class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'latest_blog_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Blog.objects.all()


class BlogView(generic.DetailView):
    model = Blog
    template_name = 'blog/blog.html'


class EntryView(generic.DetailView):
    model = Entry
    template_name = 'blog/entry.html'


def get_blog(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        form = BlogForm(request.POST)
        if form.is_valid():
            # print(form.cleaned_data['name'])
            # print(form.cleaned_data['tagline'])
            form.save()
            # form = BlogForm
            return HttpResponseRedirect('../')
    else:
        form = BlogForm()

    return render(request, 'blog/blog_form.html', {'form': form})


def get_author(request):
    user = request.user
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            # print(form.cleaned_data['name'])
            # print(form.cleaned_data['tagline'])
            form.save()
            # form = BlogForm
            return HttpResponseRedirect('../')
    else:
        form = AuthorForm()

    return render(request, 'blog/author_form.html', {'form': form})


def get_entry(request):
    user = request.user
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        form = EntryForm(request.POST)
        if form.is_valid():
            # print(form.cleaned_data['name'])
            # print(form.cleaned_data['tagline'])
            form.save()
            # form = BlogForm
            return HttpResponseRedirect('../')
    else:
        form = EntryForm()

    return render(request, 'blog/entry_form.html', {'form': form})



def saved(request):
    template = loader.get_template("blog/blog.html")
    return HttpResponse(template.render())


def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('../')
    else:
        form = SignUpForm()

    context = {'form' : form}
    return render(request, 'registration/register.html', context)

boards/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def home(request):
    return HttpResponse('Hello, World!')

polls/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from .models import Question, Choice
from django.urls import reverse
from django.views import generic


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

blog/templates/blog/author_form.html
{% if user.is_authenticated %}
    <h2>You name is: {{ user.username }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
{% else %}
    <h2>You are not logged in.</h2>
    <a href="../accounts/login"><p>Click here to log in</p></a>
{% endif %}

blog/templates/blog/blog.html
{% if user.is_authenticated %}
    <h2>You name is: {{ user.username }}</h2>
{% else %}
    <h2>You are not logged in.</h2>
    <a href="../accounts/login"><p>Click here to log in</p></a>
{% endif %}


<h1>{{ blog.name }}</h1>
<h2>{{ blog.tagline  }}</h2>

{% if blog.entry_set %}
    <ul>
    {% for entry in blog.entry_set.all %}
        <li>
<!--            <h2>{{ entry.blog }}</h2>-->
            <a href="/blog/entry/{{ entry.id }}/"><h2>{{ entry.headline }}</h2></a>
<!--            <h3>{{ entry.body_text }}</h3>-->
            <p>Published Date: {{entry.pub_date}}</p>
            <p>Author:
                {% for authors in entry.authors.all %}
                    {{authors}}
                {% endfor %}</p>
            <p>Comments: {{entry.number_of_comments}}</p>
            <p>Ratings: {{entry.rating}}</p>
            <br>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No entries are available.</p>
{% endif %}

{% if user.is_authenticated %}
    <a href="../create_entry/"><p>Create an entry</p></a>
{% else %}
    <h2>You are not logged in.</h2>
    <a href="accounts/login"><p>log in to create an entry</p></a>
{% endif %}

blog/templates/blog/blog_form.html
{% if user.is_authenticated %}
    <h2>You name is: {{ user.username }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
{% else %}
    <h2>You are not logged in.</h2>
    <a href="../accounts/login"><p>Click here to log in</p></a>
{% endif %}

blog/templates/blog/entry.html
{% if user.is_authenticated %}
    <h2>You name is: {{ user.username }}</h2>
{% else %}
    <h2>You are not logged in.</h2>
{% endif %}

<h2>{{ entry.headline }}</h2>
<p><a href="../../{{entry.blog.id}}">{{entry.blog}}</a></p>
<h3>{{ entry.body_text }}</h3>
<br>
<p>Published Date: {{entry.pub_date}}</p>
<p>Author:
    {% for authors in entry.authors.all %}
        {{authors}}
    {% endfor %}</p>
<p>Comments: {{entry.number_of_comments}}</p>
<p>Ratings: {{entry.rating}}</p>

blog/templates/blog/entry_form.html
{% if user.is_authenticated %}
    <h2>You name is: {{ user.username }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
{% else %}
    <h2>You are not logged in.</h2>
    <a href="../accounts/login"><p>Click here to log in</p></a>
{% endif %}

blog/templates/blog/index.html
{% if user.is_authenticated %}
    <h2>You name is: {{ user.username }}</h2>
{% else %}
    <h2>You are not logged in.</h2>
    <a href="accounts/login"><p>Click here to log in</p></a>
{% endif %}


{% if latest_blog_list %}
    <ul>
    {% for blog in latest_blog_list %}
        <li><h3><a href="/blog/{{ blog.id }}/">{{ blog.name }}</a></h3></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No blogs are available.</p>
{% endif %}

<a href="create_blog/"><p>Create Blog</p></a>

blog/templates/blog/saved.html
<h1>Saved</h1>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>